from enum import Enum

class SecurityEventSeverity(str, Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"

class SecurityEventType(str, Enum):
    PAYMENT_REPLAY_ATTEMPT = "PAYMENT_REPLAY_ATTEMPT"
    MULTIPLE_WITHDRAWAL_ATTEMPTS = "MULTIPLE_WITHDRAWAL_ATTEMPTS"
    OTP_BRUTE_FORCE = "OTP_BRUTE_FORCE"
    REDIS_FAILURE = "REDIS_FAILURE"
    PERMISSION_VIOLATION = "PERMISSION_VIOLATION"
    SUSPICIOUS_LOGIN = "SUSPICIOUS_LOGIN"
    FRAUD_SIGNAL = "FRAUD_SIGNAL"
